COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure

  # web
  TEMPLATE_FOLDER: static
  STATIC_FOLDER: static

  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'sqlite:///app.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./conf/logging.yml
  # 日志文件存放位置
  LOGGING_PATH: ./logs
  # 上传文件存放位置
  UPLOAD_PATH: ./files
  
  MAX_CONTENT_LENGTH: 20480000


DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: CfsPd1##$$%^!DSA#FDSF